fhorinek/BB

- Utilities/Bundle/pack_fw.py
> Clarified help, usage and options.

- BB3/App/gui/widgets/widget.c
The description of the flag was inverted.
> GSpeed flag "Decimal" fixed

- BB3/App/fc/logger/csv.c
- BB3/App/fc/logger/igc.c
Change in naming schema of logger dir and file:
log/YYYY-MM/YYYY.MM.DD HH.MM.<ext>
> [logger] change of format of logger dir and filename scheme

- BB3/App/gui/tasks/menu/system/info.c
small fix to show dialog, tested with all release channels (empty version and new version available)
> [bugfix] small fix to show dialog then no new firmware is found 

- BB3/App/fc/circling.c
- BB3/App/gui/gui.c
- BB3/App/gui/gui.h
- BB3/App/gui/tasks/page/pages.c
- BB3/App/gui/tasks/page/pages.h
PoC/solution for bug when autoset page is set for circling/gliding is set and Strato crashes after several cycles
> [bugfix] gui page switching fix (circling/gliding crash)

- BB_esp_fw/main/download.c
- BB_esp_fw/main/wifi.c
- BB_esp_fw/main/wifi.h
Prevents download if WIFI is not connected
> [bugfix] prevents download when no WIFI is connected

- BB3/App/gui/widgets/types/widget_alt_graph.c
Improved lines for FT and skipped first 2 history entries.
> Fix widget_alt_graph.

- BB3/App/gui/widgets/types/widget_alt_graph.c
- BB3/App/gui/widgets/types/widget_vario_graph.c
- BB3/App/gui/widgets/widget.c
- BB3/App/gui/widgets/widget.h
- BB3/App/gui/widgets/widget_list.c
The previous code from widget_alt_graph.c was refactored into a general
time series graph and moved to widget.c.
> Added widget_vario_graph and refactor graph generation.

- Utilities/gps_spoof/igc_playback.py
This results in a smoother vario value.
> Use "Press Alt." instead of "GNSS Alt" from IGC for vario computation.

- BB3/App/config/callbacks.c
- BB3/App/config/config.h
- BB3/App/config/default_cfg.c
- BB3/App/drivers/esp/esp.c
- BB3/App/drivers/esp/protocol.c
- BB3/App/drivers/power/pwr_mng.c
- BB3/App/drivers/tft/tft.c
- BB3/App/gui/dialog.c
- BB3/App/gui/fw_notify.c
- BB3/App/gui/fw_notify.h
- BB3/App/gui/gui.h
- BB3/App/gui/gui_list.c
- BB3/App/gui/statusbar.c
- BB3/App/gui/statusbar.h
- BB3/App/gui/tasks/menu/system/info.c
- BB3/App/gui/tasks/page/pages.c
- BB3/App/lib/lv_conf.h
- BB3/App/lib/lv_theme_skybean.c
- BB3/App/system/system_thread.c
- BB3/STM32H7A3VITX_FLASH.ld
added scrolling to release note
moved lvgl memory to DTCM
make scrollbar visible
tweak splash animatioin
> Added new firmware notification

- BB3/.cproject
- BB3/App/common.h
- BB3/App/fc/fc.h
- BB3/App/fc/imu.c
- BB3/App/gui/tasks/menu/development/imu.c
> Log raw output of IMU

- BB3/App/drivers/sensors/lsm/lsm9ds1.c
- BB3/App/gui/tasks/menu/system/advanced/advanced.c
Add option to crash manually
Fix lsm9ds1 mag readout
> Update lsm9ds1.c and advanced.c

- .github/workflows/build-firmware.yml
- .gitignore
- BB3/App/system/debug_thread.h
- Dev/Setup.md
- Utilities/Bundle/pack_fw.py
- Utilities/Docker/Dockerfile
This PR:
1. Fixes a compile time issue on macOS 
2. Adds a GitHub Action to run a full Strato build for every pull request
3. Archives `strato.fw` package for each pull request
This PR builds on #246. It will fail until the the other PR is merged and the contained GitHub Action published the required Docker image.
> Automated Strato firmware PR Build

- Dev/Setup.md
> Updated developer documentation for renamed "firmware.bin" and release

- BB3/App/fc/fc.c
- BB3/App/fc/fc.h
- BB3/App/fc/logger/logger.c
- BB3/App/fc/logger/logger.h
Next step is to create flightbook and show saved statistics.
> Collect flight statistics and write into IGC

- BB3/App/etc/format.c
- BB3/App/gui/statusbar.c
Fixes https://github.com/fhorinek/BB/issues/340
> Fix buffer overflow for time24=false

- BB3/App/fc/logger/igc.c
Fixes https://github.com/fhorinek/BB/issues/349
> No invalid GPS fix in IGC files preflight buffer

- BB3/App/etc/format.c
- BB3/App/etc/format.h
- BB3/App/gui/tasks/menu/flightbook/flightbook_statistics.c
- BB3/App/gui/tasks/menu/flightbook/flightbook_statistics.h
- BB3/App/gui/tasks/menu/settings.c
For easier integration, it is a new entry in settings. I did not find an easy way to fake it into filemanager, without changing lots of stuff. So I hand it over to you, to decide on how to integrate.
> First version of flightbook statistics.

- BB3/App/gui/map/tile.c
- BB3/App/gui/polygon.c
- BB3/App/gui/polygon.h
- BB3/App/gui/tasks/menu/flightbook/flightbook_flight_map.c
- BB3/App/gui/tasks/menu/flightbook/flightbook_statistics.c
* decoupling polygon drawing from map
* changed altitude graph to polygon
* apply animation to clouds
> more gui polish

- BB3/App/fc/fc.c
- BB3/App/fc/logger/igc.c
- BB3/App/fc/logger/igc.h
- BB3/App/fc/logger/logger.c
- BB3/App/fc/logger/logger.h
- BB3/App/gui/tasks/menu/flightbook/flightbook_flight.c
Fixes https://github.com/fhorinek/BB/issues/410
> Add "timezone" to file statistics and use in GUI

- BB3/App/gui/tasks/menu/flightbook/flightbook.c
- BB3/App/gui/tasks/menu/flightbook/flightbook_flight.c
Fixes https://github.com/fhorinek/BB/issues/438
> Flightbook filemanager sorted according to NAME, not DATE

- BB3/App/gui/tasks/menu/flightbook/flightbook_statistics.c
Fixes https://github.com/fhorinek/BB/issues/444
> Fix constant string index, wrong with i18n

- BB3/App/gui/map/map_obj.c
Show cities more important than towns and all the rest
> map: different styles for different POI labels

- BB3/App/system/maps_unzip.c
> Increase prio of map_unzip to same level as GUI.

- BB3/App/common.c
- BB3/App/common.h
- BB3/App/config/config.h
- BB3/App/config/default_cfg.c
- BB3/App/fc/fc.h
- BB3/App/fc/logger/csv.c
- BB3/App/fc/logger/kml.c
- BB3/App/fc/logger/kml.h
- BB3/App/fc/logger/logger.c
- BB3/App/gui/tasks/menu/flight/flight.c
- BB3/Assets/release_note.txt
Fixes https://github.com/fhorinek/BB/issues/253
> Add KML as additional logger
